name = "EconModels"
uuid = "83d17450-d01b-4a71-beba-34e535f4a9bd"
version = "1.0.0-DEV"
authors = ["Caleb Langdon"]

[deps]
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QuantEcon = "fcd29c91-0bd7-5a09-975d-7ac3f643a60c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
ConcreteStructs = "0.2.3"
DataFrames = "1.7.0"
Distributions = "0.25.119"
ForwardDiff = "1.2.0"
Interpolations = "0.15.1, 0.16"
LinearAlgebra = "1.11.0"
NLsolve = "4.5.1"
Optim = "1.12.0"
Plots = "1.40.13"
ProgressMeter = "1.10.4"
QuantEcon = "0.16.6, 0.17"
Random = "1.11.0"
Roots = "2.2.10"
SparseArrays = "1.11.0"
Statistics = "1.11.1"
StatsBase = "0.34.6"
Tullio = "0.3.8"
UnPack = "1.0.2"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
